<a href="https://colab.research.google.com/github/PEJ12/Data_Science/blob/main/W3L2_Python_Fast_Review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PNUCSE 데이터과학입문  
## 3주차 실습자료  
### 교강사: 박영진, youngjinpark@pusan.ac.kr
---

## 실습 목표

- Python Review
- Types
- Array


#Python Review

In [ ]:
# p.4
print(64 / 8)
print(64 // 8) #정수 나눗셈
print(65//8)
print(65 % 8)

8.0
8
8
1


In [ ]:
# p.5
hours_per_wk = 24 * 7
print(hours_per_wk)

168


In [ ]:
# p.8, 에러 발생 유도함.
abs(-1, 2)

TypeError: abs() takes exactly one argument (2 given)

In [ ]:
abs(-1.2)

1.2

In [ ]:
# p.8
a = abs(-10)
print(a)

10


In [ ]:
# p.8
a = round(number=12.34) #반올림, 함수 이름에 마우스 갖다대면 설명나옴 (소수점 버린다고?)
print(a)
a = round(number=12.74)
print(a)
#a = round(num = 1.1) 이렇게 하면 에러남, number을 써라고 round에 정의되어있다.

12
13


In [ ]:
# p.8
abs?

#Types

In [ ]:
# p.10, float형 정밀도 확인을 위한 코드 / 안전하지않음
#소수점 16자리 부분에서 값이 보장안된다.
a = 1.000005
b = 1.0000000000000005 #0이 15개
c = 1.00000000000000005
print(a)
print(b) #0이 15개에 4
print(c)

1.000005
1.0000000000000004
1.0


In [ ]:
# p.11
a = int('12')
b = float('1.2')
print(a + b)

13.2


In [ ]:
# p.11
a = '12'
b = '1.2'
print(a + b)

121.2


In [ ]:
# p.11, 에러 발생 유도함.
a = str(5)
print(4 + a)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [ ]:
# p.12, 에러 발생 유도함.
a = float('one point two')

ValueError: could not convert string to float: 'one point two'

In [ ]:
float(1)

1.0

In [ ]:
# p.12
a = int(1.2)
print(a)
a = int(1.999999) #소수점 전부 삭제
print(a)

1
1


In [ ]:
# p.13, 에러 발생 유도함.
x = 3
y = '4'
z = '5.6'

#print(x + y) #에러
#print(x + int(y + z)) #고쳐보기
print(x + int(y) + float(z))
print(x + int(y) + int(float(z)))
#print(x + (int(float(y + z))))
#print(str(x) + int(y)) #에러
#print(y + float(z))

12.6
12


In [ ]:
# p.14
print(type(2))
print(type(2 + 2))
print(type('2'+ '2'))
x = 2
print(type(x))

<class 'int'>
<class 'int'>
<class 'str'>
<class 'int'>


#Arrays

In [ ]:
import numpy as np

arr1 = np.array([1,2,3])
print(arr1)
arr2 = np.array([4,5,6])
print(arr2)
print(arr1 + arr2)
print(arr1 * arr2) #요소별로 연산하므로 arr1, arr2의 길이가 같아야함

[1 2 3]
[4 5 6]
[5 7 9]
[ 4 10 18]


In [ ]:
arr = np.array([1,'2',3]) #하나의 array는 자동으로 같은 타입으로 저장
print(arr)
arr = np.array([1,2.0,3]) #다 실수로
print(arr)

['1' '2' '3']
[1. 2. 3.]


In [ ]:
# p.18
from datascience import * #리스트 형태로 array 만들고싶지 않을때 (numpy 대신)
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [ ]:
# p.18
import numpy as np
eps_arr = np.array(["noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection"])
eps_arr
#np.array : 리스트 형태로 넣어야함

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

In [ ]:
# p.19
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [ ]:
# p.19
baseline_high = 14.48
highs = np.array([baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684])
highs #앞의 셀과 동일한 배열 생성됨

array([ 13.6  ,  14.387,  14.585,  15.164])

In [ ]:
# p.19
baseline_low = 3.00
lows = np.array([baseline_low - 0.872, baseline_low - 0.629, baseline_low - 0.126, baseline_low + 0.728])
lows

array([ 2.128,  2.371,  2.874,  3.728])

In [ ]:
# p.20
np.array([
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
])

highs - lows
# 마지막 줄의 결과만 자동 출력됨.
#np.array([...])는 생성되었지만, 셀의 마지막 줄이 아니라서 출력되지 않음.

array([ 11.472,  12.016,  11.711,  11.436])

In [ ]:
# p.21
arr = np.array([0.0, 1.0, 2.0, 3.0])

a = np.prod(arr) #요소들 다 곱하기
print(a)

b = np.sum(arr)
print(b)

c = np.all(arr) #모든게 다 t 이면 1 반환 (0.0만 False로 간주)
print(c)

d = np.any(arr)
print(d)

e = np.count_nonzero(arr)
print(e)

0.0
6.0
False
True
3


In [ ]:
# p.23
a = np.arange(5)
print(a)

b = np.arange(3, 9)
print(b)

c = np.arange(start=3, stop=9)
print(c)

#c = np.arange(start=3, end=9) 이건 에러
#print(c)

d = np.arange(1.5, -2, -0.5)
print(d)

e = np.arange(start=1.5, stop=-2, step=-0.5) #다 s로 시작하네
print(e)

[0 1 2 3 4]
[3 4 5 6 7 8]
[3 4 5 6 7 8]
[ 1.5  1.   0.5  0.  -0.5 -1.  -1.5]
[ 1.5  1.   0.5  0.  -0.5 -1.  -1.5]


In [ ]:
#내가 작성! 첫번째 문제, sum하는 게 중요!!!!!!
arr1 = np.arange(1,10000,4)
arr2 = arr1+2
sum_inv_arr1 = sum(1/arr1)
sum_inv_arr2 = sum(1/arr2)

print(4*(sum_inv_arr1-sum_inv_arr2))

3.14139265359


In [ ]:
# p.25 이 예제 직접 작성해보기
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [ ]:
# p.25
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [ ]:
# p.25
positive_terms = 1 / positive_term_denominators
negative_terms = 1 / (positive_term_denominators + 2)

4 * (sum(positive_terms) - sum(negative_terms))#정밀도를 만까지해서 오차 존재 (3.141592...)

3.1413926535917955

In [ ]:
#내가 작성
arr2 = np.arange(2,10000001,2)
arr1 = arr2-1
arr3 = arr2+1

n1 = np.prod(arr2/arr1) #첫 항
n2 = np.prod(arr2/arr3) #두번째 항
print(2*n1*n2)

3.14159249651


In [ ]:
# p.26 직접 해보기
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

np.float64(3.1415910827951143)